version: '3.8'

services:
  euronextv1:
    image: euronext
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: euronextdb
      POSTGRES_USER: euronextuser
      POSTGRES_PASSWORD: euronext123
